spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: z123456
    url: jdbc:mysql:///manager?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 1
      min-idle: 0
    timeout: 0
  application:
    name: home
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/